name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ]
        # TODO : add windows

    steps:
    - uses: actions/checkout@v2
    - name: Set up Pashmak
      uses: pashmaklang/setup-pashmak@master
      with:
        pashmak-version: 0.8.3

    - name: Running Tests
      shell: bash
      run: |
        git config --global user.email '<>'
        git config --global user.name 'robot'
        if [ "$RUNNER_OS" == "Windows" ]; then
            pashmak tests/run.pashm
        else
            make all
        fi

    name: Test ${{ matrix.os }}
